### PR TITLE
Updated 5.9.0

### PR DESCRIPTION
**Pull request by SwissalpS**
- overhauled English language
- overhauled French language
- adds Spanish locale
- adds German locale
- adds mtt integration testing
- adds github workflow for mtt
- refactores handle_command
- standardizes usage of table.getn() (nothing crucial in this mod)
- standardizes variables to have same format and same name for same purpouse
- **stores password hashes instead of cleartext**
- DB-fix also adds missing owners to members
- DB-fix also converts cleartext passwords to hashes
- fixes some situations where admins couldn't do things
- fixes display of dynamic admin priv and registration
- alows uppercase for subcommands
- adds valid_password() for cleaner checks
- ensures that existing factions don't get overwritten (by other mods using 'API')
- adds disband-hook registration for other mods to get notified of disbanded factions

### CODE REVIEW

**Comment by BuckarooBanzay** [comment]
what's the difference from this to #11?

**Comment by SwissalpS** [comment]
See #8

#11 has all of the changes in #12 (this PR) minus the password hashing.
Idea is to merge #11 and make at least a tag or a release package for last MT 5.0.0 support. Then merge #12 for 5.9.0+ support.
Or put #12 on a different branch. It's up for discussion/decission.

**Comment by wsor4035** [comment]
copied from the previous pr

> support of the last two major releases of minetest is generally accepted minimum, however not hard set opposed 🤷

**Comment by wsor4035** [comment]
though 5.10 is around the corner....so would fix that

**Comment by SwissalpS** [comment]
It has been three months without any issues being raised etc.
Luanti 5.10. is out for a hot minute too and I've tagged the last ref compatible with pre-5.9.
and cleartext passwords.

I intend to merge this within a day, maybe two but certainly this year...

**Review by BuckarooBanzay — APPROVED** [review]
didn't test but looks good :+1:

**Pull request merged**
